apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
spec:
  storageClassName: manual
  volumeName: gitea-pv
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
