apiVersion: v1
kind: Service
metadata:
  name: gitea
spec:
  type: NodePort
  selector:
    app: gitea
  ports:
  - name: ssh
    port: 22
    targetPort: 222
  - name: web
    port: 3000
    targetPort: 3000
    nodePort: 30300
