# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-watcher
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
# rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: watch-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: airflow
roleRef:
  kind: Role
  name: pod-watcher
  apiGroup: rbac.authorization.k8s.io