apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/bash
        - -c
        args: 
        - minio server /data --console-address :9090
        volumeMounts:
        - mountPath: /data
          name: minio-data 
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
          - containerPort: 9090
          - containerPort: 9000

      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-pvc
